project: adv_udivia_trainval_3090_personality
program: main_adversarial.py
name: adversarial
# general args
# model
arch : perceiver

depth : 5
num_latents : 128
latent_dim : 128

num_outputs : 1

#arch : infomax
# train
lr : 0.004
epochs : 30

num_workers : 0
batch_size : 2

distributed : False
gpus : 1
optimizer : lamb
scheduler : constant
is_baseline : 1
seed: 1995
eval_every_n_epoch : 1
target_personality : 0
modalities: [text_facebody_audio]
#wandb_mode: offline









