
project: adv_udivia_trainval_3090_personality_inc
program: main_adversarial.py
#project: tmp
#program: tmp.py

name: adversarial
method: grid
parameters:
  arch:
    values: [ 'perceiver' ]
  depth:
    values: [5]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [ 6, 1995, 1996]
  modalities:
     values: [ "text_facebody_audio"]
#    values: ["text", "facebody", "audio", "text_facebody", "text_audio", "facebody_audio", "text_facebody_audio"]


  epochs:
    values: [10]

  target_personality:
    values: [0]

  eval_every_n_epoch:
    values: [1]


  results_dir:

    values: ["/DATA/jj/affection/adv_results/s_inc"]

  num_outputs:
    values: [1]


metric:
  goal: minimize
  name: test_loss








