
project: postp_udivia_trainval_3090_personality
program: main_post.py

name: postProcessing
method: grid
parameters:
  arch:
    values: [ 'perceiver' ]
  depth:
    values: [5]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [ 6, 1995, 1996]
  modalities:

    values: ["text", "facebody", "audio", "text_facebody", "text_audio", "facebody_audio", "text_facebody_audio"]

  epochs:
    values: [30]

  target_personality:
    values: [0, 1, 2, 3, 4]

#  target_sensitive_group:
#    values: [ "age", "gender"]

  eval_every_n_epoch:
    values: [1]



  results_dir:

    values: ["/DATA/jj/affection/postP_results/pretrain"]

  num_outputs:
    values: [1]


metric:
  goal: minimize
  name: test_loss








