project: perceiver_affection_v100_age26_trainval
name: 5
# general args
# model
arch : infomax


# train
dataset : udiva
lr : 0.001
epochs : 60

num_workers : 4
batch_size : 32

distributed : False
gpus : 1
optimizer : adam
scheduler : constant
is_baseline : 1
seed: 1995
eval_every_n_epoch : 1
#wandb_mode: offline
alpha : 0.3
beta : 0.1
modalities : ['text_audio_facebody']








