project: NWS_FC
name: mnist
## general args
# model
n_emb : 512
beta : 0.1

# train
lr : 0.01
epochs : 16
num_workers : 4
batch_size : 32
dataset : mnist
distributed : False
is_pretraining : 1
eval_every_n_epoch : 1
gpus : 1
optimizer : adam
scheduler : cosine

# sgd lr 0.01 does not work





