project: perceiver_affection
name: text_facebody
## general args
# model
arch : perceiver

depth : 3
num_latents : 128
latent_dim : 128
cross_heads : 1
latent_heads : 8
cross_dim_head : 64
latent_dim_head : 64
num_outputs : 5

# train
lr : 0.004
epochs : 60

num_workers : 4
batch_size : 128

distributed : False
eval_every_n_epoch : 10
gpus : 1
optimizer : lamb
scheduler : multistep
seed : 1995
#milestones : [84, 102, 114]







