project: perceiver_affection_test
program: main.py
#project: tmp
#program: tmp.py

name: baseline
method: grid
parameters:
  depth:
    values: [5]

  num_latents:
    values: [256]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: [ "constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]
  modalities:
    #[
    values:
    # comment out the following line to run all modalities

      ["text", "facebody", "audio", "senti_speech_time", "text_facebody", "text_audio", "text_senti_speech_time", "facebody_audio", "facebody_senti_speech_time", "audio_senti_speech_time", "text_facebody_audio", "text_facebody_senti_speech_time", "text_audio_senti_speech_time", "facebody_audio_senti_speech_time", "text_facebody_audio_senti_speech_time"]
  is_baseline:
    values: [1]

  results_dir:
    values: ["results/test"]


  finetune:
    values: [ "/home/rootuser/proj/perceiver_affection/results/trainval_bul_baseline_right_uniqueMean/xxx_lr0.004_e60_seed1995_optlamb_bs128_beta0.5_alpha_0.1_gamma_1/last.ckpt" ]

  test_only:
    values: [1]
#40 epoch don't consider the talk

metric:
  goal: minimize
  name: test_loss








