project: perceiver_affection_baseline_trainval_bul
program: main.py
#project: tmp
#program: tmp.py

name: baseline
method: grid
parameters:
  depth:
    values: [5]

  num_latents:
    values: [256]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: [ "constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]
  modalities:
    #[
    values:
    # comment out the following line to run all modalities
      ["text", "facebody", "audio", "senti_speech_time", "text_facebody", "text_audio", "text_senti_speech_time", "facebody_audio", "facebody_senti_speech_time", "audio_senti_speech_time", "text_facebody_audio", "text_facebody_senti_speech_time", "text_audio_senti_speech_time", "facebody_audio_senti_speech_time", "text_facebody_audio_senti_speech_time"]
  epochs:
    values: [60, 100]

  is_baseline:
    values: [1]

  results_dir:
    values: ["results/trainval_bul"]

#40 epoch don't consider the talk

metric:
  goal: minimize
  name: test_loss








