project: perceiver_affection_hyper2


program: main.py
name: baseline_hyper
method: grid
parameters:
  depth:
    values: [3, 4]

  num_latents:
    values: [16]
  latent_dim:
    values: [512]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ['multistep'] #, "constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1993, 1994, 1995, 1996 , 2000]

  epochs:
    values: [60]

  is_baseline:
    values: [1]


metric:
  goal: minimize
  name: test_loss








