project: perceiver_affection_kd_trainval


program: main.py
name: mtl_seed
method: grid
parameters:
  depth:
    values: [5]

  num_latents:
    values: [256]
  latent_dim:
    values: [128]
  lr:
    values: [0.001, 0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]

  epochs:
    values: [5, 10, 20]

  beta:
    values: [0.1, 0.5, 1.0]
  alpha:
    values: [0.99]
  finetune:
    values: ["/home/rootuser/proj/perceiver_affection/results/sweep_mtl_trainval_devicebul/text_facebody_audio_lr0.004_e25_seed1995_optlamb_bs128_beta0.5_alpha_0.99/last.ckpt"]

  modalities:
    values: ["text_facebody_audio"]

  is_baseline:
    values: [0]

  is_incremental:
    values: [1]

  use_distribution_loss:
    values: [1]

  target_sensitive_group:
    values: ["age"]

  results_dir:
    values: ["results/sweep_mtl_trainval/third"]

  batch_size:
    values: [128]
metric:
  goal: minimize
  name: test_loss








