project: perceiver_affection_hyper


program: main.py
name: baseline_hyper
method: grid
parameters:
#  depth:
#    values: [4, 6]
#  lr:
#    values: [0.004, 0.02, 0.01]
#
#  wandb_mode:
#    values: ["online"]
#  scheduler:
#    values: ["multistep", "cosine"]
#  optimizer:
#        values: ["lamb", 'sgd', "adam"]
#
#  epochs:
#    values: [30, 60]
  lr:
    values: [0.01, 0.02, 0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["cosine", 'multistep']
  optimizer:
        values: ["adam",  "lamb"]
  seed:
    values: [1995, 0, 36]

  epochs:
    values: [30, 60]

  is_baseline:
    values: [1]


metric:
  goal: minimize
  name: test_loss








