project: perceiver_affection_mtl_mix


program: main.py
name: mtl_seed
method: grid
parameters:
  depth:
    values: [3]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.001, 0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]

  epochs:
    values: [10]

#  beta:
#    values: [0.1, 0.5, 1.0]
  alpha:
    values: [0.01, 0.99]
  finetune:
    values: ["/vol/jj/proj/perceiver_affection/checkpoints/lr0.004_e60_seed1995_optlamb_bs128_schedulerconstant_beta0.5_numlatent128_latentdim_128/last.ckpt"]

  is_baseline:
    values: [0]

  use_distribution_loss:
    values: [1]
metric:
  goal: minimize
  name: test_loss








