#project: perceiver_affection_baseline_trainval_a5000
project: perceiver_affection_baseline_trainval_3090_final
program: main.py
#project: tmp
#program: tmp.py

name: baseline
method: grid
parameters:
  arch:
    values: [ 'perceiver' ]
  depth:
    values: [5]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [ 6, 1995, 1996]
  modalities:
    #[
    values:
    # comment out the following line to run all modalities
#      ['text']
      ["text", "facebody", "audio", "senti_speech_time", "text_facebody", "text_audio", "text_senti_speech_time", "facebody_audio", "facebody_senti_speech_time", "audio_senti_speech_time", "text_facebody_audio", "text_facebody_senti_speech_time", "text_audio_senti_speech_time", "facebody_audio_senti_speech_time", "text_facebody_audio_senti_speech_time"]
  epochs:
    values: [60]

  is_baseline:
    values: [1]

  results_dir:
#    values: ["results/trainval_a5000_baseline_right_uniqueMean"]
    values: ["/DATA/jj/affection/results/trainval_3090_baseline_final"]
#40 epoch don't consider the talk

metric:
  goal: minimize
  name: test_loss








