#project: perceiver_affection_different_modality
#program: main.py
project: tmp
program: tmp.py

name: baseline_hyper
method: grid
parameters:
  depth:
    values: [3]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: [ "constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]
  modalities:
#    values: [ text, facebody, text facebody]
    values: [ "text", "facebody", "audio", "senti", "speech", "time", "talkturn", "text,facebody", "text,facebody,audio", "text,facebody,audio,senti", "text,facebody,audio,senti,speech", "text,facebody,audio,senti,speech,time", "text,facebody,audio,senti,speech,time,talkturn"]
  epochs:
    values: [60 ]

  is_baseline:
    values: [1]


metric:
  goal: minimize
  name: test_loss








