project: perceiver_affection_mtl_hyper


program: main.py
name: mtl_seed
method: grid
parameters:
  depth:
    values: [3]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [0.001, 0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["multistep", "constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]

  epochs:
    values: [10, 30, 60]

  beta:
    values: [0.1, 0.5, 1.0]
  finetune:
    values: ["", "/vol/jj/proj/perceiver_affection/results/baseline/lr0.004_e60_seed36_optlamb_bs128_schedulerconstant/last.ckpt"]

  is_baseline:
    values: [0]
metric:
  goal: minimize
  name: test_loss








