project: perceiver_affection_spd_trainval_a5000
#project: perceiver_affection_spd_trainval_3090

program: main.py
name: mtl_seed
method: grid
parameters:
  arch:
    values: [ 'perceiver' ]
  depth:
    values: [5]

  num_latents:
    values: [128]
  latent_dim:
    values: [128]
  lr:
    values: [ 0.001, 0.004]

  wandb_mode:
    values: ["online"]
  scheduler:
    values: ["constant"]
  optimizer:
        values: ["lamb"]
  seed:
    values: [0, 1993, 2023]

  epochs:
    values: [5]

#  beta:
#    values: [0.1, 0.5, 1.0]
#  alpha:
#    values: [0.5,0.8, 0.9,0.1]
  # gamma bigger than 100 will have big impact on the val loss for audio
  gamma:
#    values: [2, 2.5, 3, 5]
    values: [ 5 ]
  batch_size:
    values: [128]
  finetune:
    values: [ "/vol/jj/proj/perceiver_affection/results/trainval_a5000_baseline_right_uniqueMean/gender/xxx_lr0.004_e60_seedsss_optlamb_bs128_beta0.5_alpha_0.1_gamma_1/last.ckpt" ]
#    values: ["/home/rootuser/proj/perceiver_affection/results/trainval_3090_baseline_right_uniqueMean/gender/xxx_lr0.004_e60_seedsss_optlamb_bs128_beta0.5_alpha_0.1_gamma_1/last.ckpt"]
  modalities:
#    values: [ "text"]
    values:  [  "text","facebody", "audio", "senti_speech_time", "text_facebody", "text_audio", "text_senti_speech_time", "facebody_audio", "facebody_senti_speech_time", "audio_senti_speech_time", "text_facebody_audio", "text_facebody_senti_speech_time", "text_audio_senti_speech_time", "facebody_audio_senti_speech_time", "text_facebody_audio_senti_speech_time"] #["text", "facebody", "audio"]
  is_baseline:
    values: [0]

  use_distribution_loss:
    values: [1]

  results_dir:
    values: ["results/trainval_a5000_mtl_uniqueMean_from60"]
#    values: ["results/trainval_3090_mtl_uniqueMean_from60"]
  eval_every_n_epoch:
    values: [1]
  target_sensitive_group:
    values: [ "age", "gender" ]
metric:
  goal: minimize
  name: test_loss








