project: perceiver_affection_different_modality
name: text_facebody
## general args
# model
arch : perceiver

depth : 3
num_latents : 128
latent_dim : 128
cross_heads : 1
latent_heads : 8
cross_dim_head : 64
latent_dim_head : 64
num_outputs : 5

# train
lr : 0.001
epochs : 10

num_workers : 4
batch_size : 128

distributed : False
eval_every_n_epoch : 10
gpus : 1
optimizer : lamb
scheduler : multistep
seed : 1995
is_baseline : 0
alpha : 0.5
use_distribution_loss : 1
is_incremental : 1
target_sensitive_group : 'age'
#finetune: "H:/tmp_results/lr0.001_e10_seed1995_optlamb_bs128_schedulermultistep_beta0.5_numlatent128_latentdim_128/last.ckpt"
finetune: "/vol/jj/proj/perceiver_affection/results/second/text_facebody_lr0.001_e10_seed1995_optlamb_bs128_beta0.5/last.ckpt"
#milestones : [84, 102, 114]







