project: perceiver_affection_hyper_trainval

program: main.py
name: baseline_hyper
method: grid
parameters:
  depth:
    values: [5]

  num_latents:
    values: [256]
  latent_dim:
    values: [128]
  lr:
    values: [0.004]
  modalities:
    values: [ "text_facebody_audio"]
  wandb_mode:
    values: ["online"]
  scheduler:
    values: [ "constant"] #'multistep'] #,
  optimizer:
        values: ["lamb"]
  seed:
    values: [1995]

  epochs:
    values: [60]

  is_baseline:
    values: [1]

  results_dir:
    values: ["results/new_checkpoints2"]


metric:
  goal: minimize
  name: test_loss








