project: perceiver_affection_third_trainval_v100_age26
name: text_facebody
## general args
# model
arch : perceiver

depth : 5
num_latents : 128
latent_dim : 128
cross_heads : 1
latent_heads : 8
cross_dim_head : 64
latent_dim_head : 64
num_outputs : 5

# train
lr : 0.004
epochs : 5

num_workers : 4
batch_size : 128

distributed : False
eval_every_n_epoch : 1
gpus : 1
optimizer : lamb
scheduler : constant
seed : 1995
is_baseline : 0
beta : 1.0
gamma : 5
use_distribution_loss : 1
is_incremental : 1
target_sensitive_group : 'age'
#finetune: "H:/tmp_results/lr0.001_e10_seed1995_optlamb_bs128_schedulermultistep_beta0.5_numlatent128_latentdim_128/last.ckpt"
#finetune: "/vol/jj/proj/perceiver_affection/results/second/text_facebody_lr0.001_e10_seed1995_optlamb_bs128_beta0.5/last.ckpt"








